### ISSUE TITLE
Issue With Entity.java

### ISSUE THREAD

**Issue by modernham** [patrickhoey/MasteringLibGDXGameDevelopment_CodeBundle#1]
When attempting to compile this source, I can only do so by comenting out the cast statements in the setDirection Method in Entity.java.
I have an issue with assigning the current frame because:
"Error:(216, 63) java: incompatible types: java.lang.Object cannot be converted to com.badlogic.gdx.graphics.g2d.TextureRegion"
on these lines: 
"_currentFrame = _walkDownAnimation.getKeyFrame(_frameTime);"

**Comment by patrickhoey** [comment]
I would recommend compiling with the version of LibGDX that was originally compiled with this source. The code bundle that follows the book at the time it was written was compiled with LibGDX v1.5.5. I did update the latest source a little while ago (https://github.com/patrickhoey/BludBourne) to compile with LibGDX v.1.9.5. Hope this helps.
